name: Example Workflow
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.images }}
    strategy:
      matrix:
        images: ["ubuntu-latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Install PowerShell & Git
      run: sudo apt install -y git powershell
    - name: Clone CI repository
      run: |
        git clone https://github.com/ProfileID/powershell-ci /tmp/powershell-ci
        chmod 755 -R /tmp/powershell-ci
    - name: Run check.ps1
      run: pwsh /tmp/powershell-ci/check.ps1 -Path $GITHUB_WORKSPACE