name: example
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.images }}
    strategy:
      matrix:
        images: ["ubuntu-latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Clone Powershell analyze repository
      run: |
        sudo apt install -y git
        git clone https://github.com/ProfileID/powershell-ci /tmp/powershell-ci
        chmod 755 -R /tmp/powershell-ci
    - name: Install Powershell
      run: |
        sudo apt install -y powershell
    - name: Run analyze
      run: |
        ./tmp/powershell-ci/build.ps1 -path $GITHUB_WORKSPACE