name: tests
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.images }}
    strategy:
      matrix:
        images: ["ubuntu-latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Install powershell & set execute permissions
      run: |
        sudo apt install -y powershell
        chmod 755 -R $GITHUB_WORKSPACE
    - name: Run check.ps1
      run: |
        cd $GITHUB_WORKSPACE
        ./check.ps1